layout: post
mathjax: true
title: Snake Eating Itself
profile: false
description: Notes about Cognitive Science, Programming, and Language
show_downloads: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
